---
title: "Dose-Response Curves"
output: html_document
params:
 drm_obj: NA
 col: NA
 lty: NA
 lwd: NA
 cex: NA
 pch: NA
 gridsize: NA
 log: NA
 cex.lab: NA
 cex.axis: NA 
 xlab: NA
 xlim: NA
 ylab: NA
 ylim: NA
 legend: NA
 legendPos: NA
 cex.legend: NA
 box_lwd: NA
             
---

```{r setup, include=FALSE}
library(drc)
```


```{r, echo=FALSE}
summary(params$drm_obj)
```

```{r, echo=FALSE, fig.width=10}
plot(params$drm_obj,
             type = "all",
             #colors 
             col = params$col,#user
             #& aesthetics
             lty = params$lty, #user - linetype
             lwd = params$lwd, #line thickness
             pch = params$pch, #user - points style
             cex = params$cex, #user
             gridsize = params$gridsize,#, #user - smoothnest of fit
             # #axes & labels
             log = params$log,#user
             cex.lab = params$cex.lab, #user
             cex.axis = params$cex.axis, #user
             xlab = params$xlab, #user
             xlim = params$xlim, #user
             ylab = params$ylab, #user
             ylim = params$ylim,#user
             #legend
             legend = params$legend, #user
             #legendText = user_legendText(), #user
             legendPos = params$legendPos, #user
             cex.legend = params$cex.legend, #user
             bty = "l") #user
        box(lwd = params$box_lwd, bty = "l") #user
        
```

